# Form implementation generated from reading ui file 'pag.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(952, 709)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(131, 7, 45);\n"
"font: 18pt \"Calibri\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 0, 241, 181))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("IMG_0652.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 190, 111, 21))
        self.label_2.setObjectName("label_2")
        self.txt_user = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_user.setEnabled(True)
        self.txt_user.setGeometry(QtCore.QRect(330, 210, 341, 41))
        self.txt_user.setAcceptDrops(True)
        self.txt_user.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(19, 19, 19);\n"
"border-radius:12px;\n"
"")
        self.txt_user.setUndoRedoEnabled(True)
        self.txt_user.setAcceptRichText(True)
        self.txt_user.setObjectName("txt_user")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 260, 141, 21))
        self.label_3.setObjectName("label_3")
        self.buttonlogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buttonlogin.setGeometry(QtCore.QRect(330, 370, 191, 81))
        self.buttonlogin.setStyleSheet("QPushButton{\n"
"background-color: rgb(243, 205, 179);\n"
"color: rgb(19, 19, 19);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(198, 123, 105);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(198, 123, 155);\n"
"}")
        self.buttonlogin.setObjectName("buttonlogin")
        self.txt_pass = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_pass.setEnabled(True)
        self.txt_pass.setGeometry(QtCore.QRect(330, 290, 341, 41))
        self.txt_pass.setAcceptDrops(True)
        self.txt_pass.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(19, 19, 19);\n"
"border-radius:12px;\n"
"")
        self.txt_pass.setUndoRedoEnabled(True)
        self.txt_pass.setAcceptRichText(True)
        self.txt_pass.setObjectName("txt_pass")
        self.lbl_message = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_message.setGeometry(QtCore.QRect(340, 480, 301, 111))
        self.lbl_message.setText("")
        self.lbl_message.setObjectName("lbl_message")
        self.capimg = QtWidgets.QLabel(parent=self.centralwidget)
        self.capimg.setGeometry(QtCore.QRect(20, 10, 171, 161))
        self.capimg.setText("")
        self.capimg.setPixmap(QtGui.QPixmap("../cafesfotos/2022-02_cappuccino_1.png"))
        self.capimg.setScaledContents(True)
        self.capimg.setObjectName("capimg")
        self.capmenos = QtWidgets.QPushButton(parent=self.centralwidget)
        self.capmenos.setGeometry(QtCore.QRect(20, 200, 75, 23))
        self.capmenos.setObjectName("capmenos")
        self.capmas = QtWidgets.QPushButton(parent=self.centralwidget)
        self.capmas.setGeometry(QtCore.QRect(110, 200, 75, 23))
        self.capmas.setObjectName("capmas")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, -50, 941, 681))
        self.listWidget.setObjectName("listWidget")
        self.exmas = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exmas.setGeometry(QtCore.QRect(360, 200, 75, 23))
        self.exmas.setObjectName("exmas")
        self.expresoimg = QtWidgets.QLabel(parent=self.centralwidget)
        self.expresoimg.setGeometry(QtCore.QRect(270, 10, 171, 161))
        self.expresoimg.setText("")
        self.expresoimg.setPixmap(QtGui.QPixmap("../cafesfotos/2022-02_espresso-americano_1.png"))
        self.expresoimg.setScaledContents(True)
        self.expresoimg.setObjectName("expresoimg")
        self.exmenos = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exmenos.setGeometry(QtCore.QRect(270, 200, 75, 23))
        self.exmenos.setObjectName("exmenos")
        self.frapmas = QtWidgets.QPushButton(parent=self.centralwidget)
        self.frapmas.setGeometry(QtCore.QRect(110, 430, 75, 23))
        self.frapmas.setObjectName("frapmas")
        self.frapimg = QtWidgets.QLabel(parent=self.centralwidget)
        self.frapimg.setGeometry(QtCore.QRect(20, 240, 171, 161))
        self.frapimg.setText("")
        self.frapimg.setPixmap(QtGui.QPixmap("../cafesfotos/2022-02_caramel-frappuccino_2.png"))
        self.frapimg.setScaledContents(True)
        self.frapimg.setObjectName("frapimg")
        self.frapmenos = QtWidgets.QPushButton(parent=self.centralwidget)
        self.frapmenos.setGeometry(QtCore.QRect(20, 430, 75, 23))
        self.frapmenos.setObjectName("frapmenos")
        self.chocomas = QtWidgets.QPushButton(parent=self.centralwidget)
        self.chocomas.setGeometry(QtCore.QRect(360, 430, 75, 23))
        self.chocomas.setObjectName("chocomas")
        self.chocimg = QtWidgets.QLabel(parent=self.centralwidget)
        self.chocimg.setGeometry(QtCore.QRect(270, 240, 171, 161))
        self.chocimg.setText("")
        self.chocimg.setPixmap(QtGui.QPixmap("../cafesfotos/2022-02_chocolate-caliente_1.png"))
        self.chocimg.setScaledContents(True)
        self.chocimg.setObjectName("chocimg")
        self.chocmenos = QtWidgets.QPushButton(parent=self.centralwidget)
        self.chocmenos.setGeometry(QtCore.QRect(270, 430, 75, 23))
        self.chocmenos.setObjectName("chocmenos")
        self.labelmenumsg = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelmenumsg.setGeometry(QtCore.QRect(370, 0, 191, 41))
        self.labelmenumsg.setObjectName("labelmenumsg")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 952, 35))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "usuario"))
        self.label_3.setText(_translate("MainWindow", "contraseña"))
        self.buttonlogin.setText(_translate("MainWindow", "Iniciar sesion"))
        self.capmenos.setText(_translate("MainWindow", "-"))
        self.capmas.setText(_translate("MainWindow", "+"))
        self.exmas.setText(_translate("MainWindow", "+"))
        self.exmenos.setText(_translate("MainWindow", "-"))
        self.frapmas.setText(_translate("MainWindow", "+"))
        self.frapmenos.setText(_translate("MainWindow", "-"))
        self.chocomas.setText(_translate("MainWindow", "+"))
        self.chocmenos.setText(_translate("MainWindow", "-"))
        self.labelmenumsg.setText(_translate("MainWindow", "Menu de compras"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
